### ISSUE TITLE
Writing logs files failed after writing a lot of log lines

### ISSUE THREAD

**Issue by jewilmeer** [koenbollen/jl#9]
I've got a process that outputs a lot of log lines, of which 33% is actual JSON. After a minute the output breaks with the following error:

```
panic: JSON decoder out of sync - data changing underfoot?
goroutine 1 [running]:
encoding/json.(*decodeState).objectInterface(0xc000263d60, 0xc000395980)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:1084 +0x2cd
encoding/json.(*decodeState).object(0xc000263d60, 0x11713c0, 0xc000395980, 0x16, 0xc000263d88, 0xc00037537b)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:623 +0x215c
encoding/json.(*decodeState).value(0xc000263d60, 0x11713c0, 0xc000395980, 0x16, 0xc0000e7e08, 0x1114da4)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:381 +0x6e
encoding/json.(*decodeState).unmarshal(0xc000263d60, 0x11713c0, 0xc000395980, 0xc000263d88, 0x0)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:179 +0x209
encoding/json.Unmarshal(0xc0000c7eeb, 0xd7, 0x115, 0x11713c0, 0xc000395980, 0xc0000c7ac7, 0x0)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:106 +0x123
main.main()
	/Users/jan-willemvandermeer/projects/go/src/github.com/koenbollen/jl/main.go:42 +0x5d3
log writing failed. Broken pipe @ io_write - <STDOUT>
log writing failed. Broken pipe @ io_write - <STDOUT>
log writing failed. Broken pipe @ io_write - <STDOUT>
```

**Comment by koenbollen** [comment]
Could you maybe provide me with a way to reproduce it? Maybe find the log line it breaks on, or record the output into a dummy script? I'll try and reproduce it as well based on your description.

**Comment by jewilmeer** [comment]
You can trigger it by outputting [this log](https://github.com/koenbollen/jl/files/3232934/processor_logs.txt), and piping it through `jl`;

```bash
cat processor_logs.txt | jl
```

**Comment by koenbollen** [comment]
Hey @jewilmeer!
I could reproduce your issue and I believe I was able to fix it: https://github.com/koenbollen/jl/pull/10

A data-race was probably causing this issue. I tried running jl with `go run -race main.go` and that found a data-race. After fixing that I could reproduce your issue anymore.

Could you maybe checkout this branch and test it for me?

**Comment by jewilmeer** [comment]
Hey Koen,

It improved it, but it would still crash every now and then. If I run the following 10 times, i would have around 3 crashes.

```
go build .
cat ~/Downloads/processor_logs.txt| ./jl
```

```
   (0.2ms)  COMMIT
[2019-05-29 14:19:11]    INFO: Issue processedpanic: JSON decoder out of sync - data changing underfoot?

goroutine 1 [running]:
encoding/json.(*decodeState).object(0xc0004060a0, 0x1171f80, 0xc00000e218, 0x16, 0xc0004060c8, 0xc000322c7b)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:672 +0x24aa
encoding/json.(*decodeState).value(0xc0004060a0, 0x1171f80, 0xc00000e218, 0x16, 0xc0000c5c50, 0x1114da4)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:381 +0x6e
encoding/json.(*decodeState).unmarshal(0xc0004060a0, 0x1171f80, 0xc00000e218, 0xc0004060c8, 0x0)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:179 +0x209
encoding/json.Unmarshal(0xc000108ebb, 0xca, 0x145, 0x1171f80, 0xc00000e218, 0x3, 0x114674f)
	/usr/local/Cellar/go/1.12.4/libexec/src/encoding/json/decode.go:106 +0x123
github.com/koenbollen/jl/structure.(*Formatter).outputFields(0xc00006c570, 0xc00015e2d0, 0xc000108ebb, 0xca, 0x145)
	/Users/jan-willemvandermeer/projects/go/src/github.com/koenbollen/jl/structure/format.go:136 +0xbe
github.com/koenbollen/jl/structure.(*Formatter).Format(0xc00006c570, 0xc00015e2d0, 0xc000108ebb, 0xca, 0x145, 0xc000108ebb, 0x0, 0x0, 0xc000108f85, 0x0, ...)
	/Users/jan-willemvandermeer/projects/go/src/github.com/koenbollen/jl/structure/format.go:83 +0x113
main.main()
	/Users/jan-willemvandermeer/projects/jl/main.go:55 +0x45b
```

**Comment by jewilmeer** [comment]
As you can see, it happens in the middle of a json message. The content of the json is printed, but the additional keys are not. Maybe that gives some pointers?

**Comment by koenbollen** [comment]
Hmm, that's weird. I did have the same issue running your logs through `jl` for a couple of times, was easy to reproduce. But with the data-race fix I could run this:
```bash
$ go build .
$ for i in `seq 1000`; do  cat ~/Downloads/processor_logs.txt; done | ./jl
... no panic ...
```
(I also ran it without the forloop a bunch of times)

Could you run it like this maybe:
```bash
$ cat ~/Downloads/processor_logs.txt | go run -race main.go cli.go
```

**Comment by jewilmeer** [comment]
Thanks for looking further into the issue. If I run the sequence, it crashes directly.

Running the last command returns:

```
Found 1 data race(s)
exit status 66
```

And further upwards the actual data race

```
   (0.2ms)  BEG==================
WARNING: DATA RACE
Read at 0x00c0001b4f38 by main goroutine:
  syscall.Write()
      /usr/local/Cellar/go/1.12.4/libexec/src/internal/race/race.go:45 +0xac
  internal/poll.(*FD).Write()
      /usr/local/Cellar/go/1.12.4/libexec/src/internal/poll/fd_unix.go:268 +0x1df
  os.(*File).Write()
      /usr/local/Cellar/go/1.12.4/libexec/src/os/file_unix.go:280 +0xa7
  main.writeBytes()
      /Users/jan-willemvandermeer/projects/jl/main.go:68 +0x75
  main.main()
      /Users/jan-willemvandermeer/projects/jl/main.go:48 +0x4b2

Previous write at 0x00c0001b4f38 by goroutine 7:
  syscall.Read()
      /usr/local/Cellar/go/1.12.4/libexec/src/internal/race/race.go:49 +0x9b
  internal/poll.(*FD).Read()
      /usr/local/Cellar/go/1.12.4/libexec/src/internal/poll/fd_unix.go:165 +0x1b6
  os.(*File).Read()
      /usr/local/Cellar/go/1.12.4/libexec/src/os/file_unix.go:263 +0xa7
  bufio.(*Scanner).Scan()
      /usr/local/Cellar/go/1.12.4/libexec/src/bufio/scan.go:213 +0x19a
  github.com/koenbollen/jl/stream.(*stream).run()
      /Users/jan-willemvandermeer/projects/go/src/github.com/koenbollen/jl/stream/logs.go:49 +0x6b

Goroutine 7 (running) created at:
  github.com/koenbollen/jl/stream.New()
      /Users/jan-willemvandermeer/projects/go/src/github.com/koenbollen/jl/stream/logs.go:44 +0x1f3
  main.main()
      /Users/jan-willemvandermeer/projects/jl/main.go:36 +0x351
==================
```

**Comment by koenbollen** [comment]
Ah. I think I see what's going on here. You've cloned the project in `~/projects/jl` and checkout the new branch there. But it's still running the old code from your GOPATH. I would remove `~/projects/go/src/github.com/koenbollen/jl` and move the new checkout to that location.
Moving to the new go modules system is still on my list.
Could you try that again?

**Comment by jewilmeer** [comment]
> Ah. I think I see what's going on here. You've cloned the project in `~/projects/jl` and checkout the new branch there. But it's still running the old code from your GOPATH. I would remove `~/projects/go/src/github.com/koenbollen/jl` and move the new checkout to that location.
> Moving to the new go modules system is still on my list.
> Could you try that again?

This did the trick! Tnx
